export default {
  assertersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'asserters',
    },
  ],
  graphersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'graphers',
    },
  ],
};